//! Function help database and autocomplete support

/// Function metadata for help and autocomplete
#[derive(Clone)]
pub struct FunctionInfo {
    pub name: &'static str,
    pub category: FunctionCategory,
    pub syntax: &'static str,
    pub description: &'static str,
    pub examples: &'static [&'static str],
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FunctionCategory {
    Math,
    Statistical,
    Logical,
    Text,
    Lookup,
    DateTime,
    Financial,
    Info,
}

impl FunctionCategory {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Math => "Math & Trig",
            Self::Statistical => "Statistical",
            Self::Logical => "Logical",
            Self::Text => "Text",
            Self::Lookup => "Lookup & Reference",
            Self::DateTime => "Date & Time",
            Self::Financial => "Financial",
            Self::Info => "Information",
        }
    }

    pub fn all() -> &'static [FunctionCategory] {
        &[
            Self::Math,
            Self::Statistical,
            Self::Logical,
            Self::Text,
            Self::Lookup,
            Self::DateTime,
            Self::Financial,
            Self::Info,
        ]
    }
}

/// Get all function definitions
pub fn get_all_functions() -> &'static [FunctionInfo] {
    FUNCTIONS
}

/// Get functions matching a prefix (for autocomplete)
pub fn get_matching_functions(prefix: &str) -> Vec<&'static FunctionInfo> {
    let prefix_upper = prefix.to_uppercase();
    FUNCTIONS
        .iter()
        .filter(|f| f.name.starts_with(&prefix_upper))
        .collect()
}

/// Get function by exact name
pub fn get_function(name: &str) -> Option<&'static FunctionInfo> {
    let name_upper = name.to_uppercase();
    FUNCTIONS.iter().find(|f| f.name == name_upper)
}

// Complete function database
static FUNCTIONS: &[FunctionInfo] = &[
    // ===== Math Functions =====
    FunctionInfo {
        name: "SUM",
        category: FunctionCategory::Math,
        syntax: "SUM(number1, [number2], ...)",
        description: "Adds all numbers in a range of cells",
        examples: &["=SUM(A1:A10)", "=SUM(1, 2, 3)", "=SUM(A1, B1, C1)"],
    },
    FunctionInfo {
        name: "ABS",
        category: FunctionCategory::Math,
        syntax: "ABS(number)",
        description: "Returns the absolute value of a number",
        examples: &["=ABS(-5)", "=ABS(A1)"],
    },
    FunctionInfo {
        name: "ROUND",
        category: FunctionCategory::Math,
        syntax: "ROUND(number, [num_digits])",
        description: "Rounds a number to a specified number of digits",
        examples: &["=ROUND(2.567, 2)", "=ROUND(A1, 0)"],
    },
    FunctionInfo {
        name: "ROUNDUP",
        category: FunctionCategory::Math,
        syntax: "ROUNDUP(number, num_digits)",
        description: "Rounds a number up, away from zero",
        examples: &["=ROUNDUP(3.14159, 2)", "=ROUNDUP(-3.1, 0)"],
    },
    FunctionInfo {
        name: "ROUNDDOWN",
        category: FunctionCategory::Math,
        syntax: "ROUNDDOWN(number, num_digits)",
        description: "Rounds a number down, toward zero",
        examples: &["=ROUNDDOWN(3.999, 0)", "=ROUNDDOWN(-3.9, 0)"],
    },
    FunctionInfo {
        name: "SQRT",
        category: FunctionCategory::Math,
        syntax: "SQRT(number)",
        description: "Returns the square root of a number",
        examples: &["=SQRT(16)", "=SQRT(A1)"],
    },
    FunctionInfo {
        name: "POWER",
        category: FunctionCategory::Math,
        syntax: "POWER(number, power)",
        description: "Returns the result of a number raised to a power",
        examples: &["=POWER(2, 8)", "=POWER(A1, 2)"],
    },
    FunctionInfo {
        name: "MOD",
        category: FunctionCategory::Math,
        syntax: "MOD(number, divisor)",
        description: "Returns the remainder after division",
        examples: &["=MOD(10, 3)", "=MOD(A1, 2)"],
    },
    FunctionInfo {
        name: "INT",
        category: FunctionCategory::Math,
        syntax: "INT(number)",
        description: "Rounds a number down to the nearest integer",
        examples: &["=INT(8.9)", "=INT(-8.9)"],
    },
    FunctionInfo {
        name: "TRUNC",
        category: FunctionCategory::Math,
        syntax: "TRUNC(number, [digits])",
        description: "Truncates a number toward zero",
        examples: &["=TRUNC(-2.9)", "=TRUNC(2.99, 1)"],
    },
    FunctionInfo {
        name: "CEILING",
        category: FunctionCategory::Math,
        syntax: "CEILING(number, [significance])",
        description: "Rounds up to a multiple of significance: negative numbers toward zero, or away from it with a negative significance. A positive number with a negative significance returns #NUM!",
        examples: &["=CEILING(2.5, 1)", "=CEILING(-2.5, 2)"],
    },
    FunctionInfo {
        name: "FLOOR",
        category: FunctionCategory::Math,
        syntax: "FLOOR(number, [significance])",
        description: "Rounds down to a multiple of significance: negative numbers away from zero, or toward it with a negative significance. A positive number with a negative significance returns #NUM!",
        examples: &["=FLOOR(2.5, 1)", "=FLOOR(-2.5, 2)"],
    },
    FunctionInfo {
        name: "SIGN",
        category: FunctionCategory::Math,
        syntax: "SIGN(number)",
        description: "Returns the sign of a number: 1 if positive, -1 if negative, 0 if zero",
        examples: &["=SIGN(10)", "=SIGN(-5)", "=SIGN(0)"],
    },
    FunctionInfo {
        name: "PI",
        category: FunctionCategory::Math,
        syntax: "PI()",
        description: "Returns the value of Pi (3.14159...)",
        examples: &["=PI()", "=PI()*A1^2"],
    },
    FunctionInfo {
        name: "EXP",
        category: FunctionCategory::Math,
        syntax: "EXP(number)",
        description: "Returns e raised to the power of a number",
        examples: &["=EXP(1)", "=EXP(A1)"],
    },
    FunctionInfo {
        name: "LN",
        category: FunctionCategory::Math,
        syntax: "LN(number)",
        description: "Returns the natural logarithm of a number",
        examples: &["=LN(2.71828)", "=LN(A1)"],
    },
    FunctionInfo {
        name: "LOG",
        category: FunctionCategory::Math,
        syntax: "LOG(number, [base])",
        description: "Returns the logarithm of a number to a specified base (default 10)",
        examples: &["=LOG(100)", "=LOG(8, 2)"],
    },
    FunctionInfo {
        name: "LOG10",
        category: FunctionCategory::Math,
        syntax: "LOG10(number)",
        description: "Returns the base-10 logarithm of a number",
        examples: &["=LOG10(100)", "=LOG10(A1)"],
    },
    FunctionInfo {
        name: "SIN",
        category: FunctionCategory::Math,
        syntax: "SIN(number)",
        description: "Returns the sine of an angle (in radians)",
        examples: &["=SIN(PI()/2)", "=SIN(A1)"],
    },
    FunctionInfo {
        name: "COS",
        category: FunctionCategory::Math,
        syntax: "COS(number)",
        description: "Returns the cosine of an angle (in radians)",
        examples: &["=COS(0)", "=COS(PI())"],
    },
    FunctionInfo {
        name: "TAN",
        category: FunctionCategory::Math,
        syntax: "TAN(number)",
        description: "Returns the tangent of an angle (in radians)",
        examples: &["=TAN(PI()/4)", "=TAN(A1)"],
    },
    FunctionInfo {
        name: "ASIN",
        category: FunctionCategory::Math,
        syntax: "ASIN(number)",
        description: "Returns the arcsine of a number (result in radians)",
        examples: &["=ASIN(0.5)", "=ASIN(A1)"],
    },
    FunctionInfo {
        name: "ACOS",
        category: FunctionCategory::Math,
        syntax: "ACOS(number)",
        description: "Returns the arccosine of a number (result in radians)",
        examples: &["=ACOS(0.5)", "=ACOS(A1)"],
    },
    FunctionInfo {
        name: "ATAN",
        category: FunctionCategory::Math,
        syntax: "ATAN(number)",
        description: "Returns the arctangent of a number (result in radians)",
        examples: &["=ATAN(1)", "=ATAN(A1)"],
    },
    FunctionInfo {
        name: "RAND",
        category: FunctionCategory::Math,
        syntax: "RAND()",
        description: "Returns a random number between 0 and 1",
        examples: &["=RAND()", "=RAND()*100"],
    },
    FunctionInfo {
        name: "RANDBETWEEN",
        category: FunctionCategory::Math,
        syntax: "RANDBETWEEN(bottom, top)",
        description: "Returns a random integer between two numbers",
        examples: &["=RANDBETWEEN(1, 100)", "=RANDBETWEEN(A1, B1)"],
    },
    FunctionInfo {
        name: "PRODUCT",
        category: FunctionCategory::Math,
        syntax: "PRODUCT(number1, [number2], ...)",
        description: "Multiplies all numbers in a range",
        examples: &["=PRODUCT(A1:A5)", "=PRODUCT(2, 3, 4)"],
    },
    FunctionInfo {
        name: "SUMPRODUCT",
        category: FunctionCategory::Math,
        syntax: "SUMPRODUCT(array1, [array2], ...)",
        description: "Multiplies corresponding range elements and returns the sum",
        examples: &[
            "=SUMPRODUCT(A1:A3, B1:B3)",
            "=SUMPRODUCT((A1:A9=\"x\")*B1:B9)",
        ],
    },
    FunctionInfo {
        name: "SUMSQ",
        category: FunctionCategory::Math,
        syntax: "SUMSQ(number1, [number2], ...)",
        description: "Returns the sum of the squares of the numbers",
        examples: &["=SUMSQ(3, 4)", "=SUMSQ(A1:A10)"],
    },
    FunctionInfo {
        name: "ATAN2",
        category: FunctionCategory::Math,
        syntax: "ATAN2(x_num, y_num)",
        description: "Returns the angle (in radians) of the point (x, y) from the x-axis. Note that x comes first",
        examples: &["=ATAN2(1, 1)", "=ATAN2(-1, -1)"],
    },
    FunctionInfo {
        name: "SINH",
        category: FunctionCategory::Math,
        syntax: "SINH(number)",
        description: "Returns the hyperbolic sine of a number",
        examples: &["=SINH(1)"],
    },
    FunctionInfo {
        name: "COSH",
        category: FunctionCategory::Math,
        syntax: "COSH(number)",
        description: "Returns the hyperbolic cosine of a number",
        examples: &["=COSH(4)"],
    },
    FunctionInfo {
        name: "TANH",
        category: FunctionCategory::Math,
        syntax: "TANH(number)",
        description: "Returns the hyperbolic tangent of a number",
        examples: &["=TANH(0.5)"],
    },
    FunctionInfo {
        name: "ASINH",
        category: FunctionCategory::Math,
        syntax: "ASINH(number)",
        description: "Returns the inverse hyperbolic sine of a number",
        examples: &["=ASINH(-2.5)"],
    },
    FunctionInfo {
        name: "ACOSH",
        category: FunctionCategory::Math,
        syntax: "ACOSH(number)",
        description: "Returns the inverse hyperbolic cosine of a number (1 or more)",
        examples: &["=ACOSH(10)"],
    },
    FunctionInfo {
        name: "ATANH",
        category: FunctionCategory::Math,
        syntax: "ATANH(number)",
        description: "Returns the inverse hyperbolic tangent of a number between -1 and 1",
        examples: &["=ATANH(0.5)"],
    },
    FunctionInfo {
        name: "DEGREES",
        category: FunctionCategory::Math,
        syntax: "DEGREES(angle)",
        description: "Converts radians to degrees",
        examples: &["=DEGREES(PI())"],
    },
    FunctionInfo {
        name: "RADIANS",
        category: FunctionCategory::Math,
        syntax: "RADIANS(angle)",
        description: "Converts degrees to radians",
        examples: &["=RADIANS(270)"],
    },
    FunctionInfo {
        name: "SQRTPI",
        category: FunctionCategory::Math,
        syntax: "SQRTPI(number)",
        description: "Returns the square root of (number * PI)",
        examples: &["=SQRTPI(2)"],
    },
    FunctionInfo {
        name: "FACT",
        category: FunctionCategory::Math,
        syntax: "FACT(number)",
        description: "Returns the factorial of a number",
        examples: &["=FACT(5)"],
    },
    FunctionInfo {
        name: "FACTDOUBLE",
        category: FunctionCategory::Math,
        syntax: "FACTDOUBLE(number)",
        description: "Returns the double factorial: n * (n-2) * (n-4) ...",
        examples: &["=FACTDOUBLE(7)"],
    },
    FunctionInfo {
        name: "COMBIN",
        category: FunctionCategory::Math,
        syntax: "COMBIN(number, number_chosen)",
        description: "Returns the number of combinations of a given size",
        examples: &["=COMBIN(8, 2)"],
    },
    FunctionInfo {
        name: "PERMUT",
        category: FunctionCategory::Math,
        syntax: "PERMUT(number, number_chosen)",
        description: "Returns the number of ordered arrangements of a given size",
        examples: &["=PERMUT(100, 3)"],
    },
    FunctionInfo {
        name: "GCD",
        category: FunctionCategory::Math,
        syntax: "GCD(number1, [number2], ...)",
        description: "Returns the greatest common divisor",
        examples: &["=GCD(24, 36)", "=GCD(A1:A5)"],
    },
    FunctionInfo {
        name: "LCM",
        category: FunctionCategory::Math,
        syntax: "LCM(number1, [number2], ...)",
        description: "Returns the least common multiple",
        examples: &["=LCM(24, 36)"],
    },
    FunctionInfo {
        name: "QUOTIENT",
        category: FunctionCategory::Math,
        syntax: "QUOTIENT(numerator, denominator)",
        description: "Returns the integer part of a division",
        examples: &["=QUOTIENT(5, 2)", "=QUOTIENT(-10, 3)"],
    },
    FunctionInfo {
        name: "MROUND",
        category: FunctionCategory::Math,
        syntax: "MROUND(number, multiple)",
        description: "Rounds to the nearest multiple. Mixed signs return #NUM!",
        examples: &["=MROUND(10, 3)", "=MROUND(1.3, 0.2)"],
    },
    FunctionInfo {
        name: "EVEN",
        category: FunctionCategory::Math,
        syntax: "EVEN(number)",
        description: "Rounds away from zero to the nearest even integer",
        examples: &["=EVEN(1.5)", "=EVEN(-1)"],
    },
    FunctionInfo {
        name: "ODD",
        category: FunctionCategory::Math,
        syntax: "ODD(number)",
        description: "Rounds away from zero to the nearest odd integer",
        examples: &["=ODD(1.5)", "=ODD(-2)"],
    },
    FunctionInfo {
        name: "ROMAN",
        category: FunctionCategory::Math,
        syntax: "ROMAN(number, [form])",
        description: "Converts a number (0-3999) to Roman numerals; form 0 is classic, 1-4 more concise",
        examples: &["=ROMAN(499)", "=ROMAN(499, 4)"],
    },
    FunctionInfo {
        name: "ARABIC",
        category: FunctionCategory::Math,
        syntax: "ARABIC(text)",
        description: "Converts Roman numerals to a number",
        examples: &["=ARABIC(\"MCMXII\")"],
    },
    FunctionInfo {
        name: "BASE",
        category: FunctionCategory::Math,
        syntax: "BASE(number, radix, [min_length])",
        description: "Converts a number to text in another base (2-36)",
        examples: &["=BASE(15, 2, 8)", "=BASE(255, 16)"],
    },
    FunctionInfo {
        name: "DECIMAL",
        category: FunctionCategory::Math,
        syntax: "DECIMAL(text, radix)",
        description: "Converts text in another base (2-36) to a number",
        examples: &["=DECIMAL(\"FF\", 16)"],
    },
    FunctionInfo {
        name: "CEILING.MATH",
        category: FunctionCategory::Math,
        syntax: "CEILING.MATH(number, [significance], [mode])",
        description: "Rounds up to a multiple of significance; a nonzero mode rounds negative numbers away from zero",
        examples: &["=CEILING.MATH(24.3, 5)", "=CEILING.MATH(-5.5, 2, -1)"],
    },
    FunctionInfo {
        name: "FLOOR.MATH",
        category: FunctionCategory::Math,
        syntax: "FLOOR.MATH(number, [significance], [mode])",
        description: "Rounds down to a multiple of significance; a nonzero mode rounds negative numbers toward zero",
        examples: &["=FLOOR.MATH(24.3, 5)", "=FLOOR.MATH(-5.5, 2, -1)"],
    },
    // ===== Statistical Functions =====
    FunctionInfo {
        name: "AVERAGE",
        category: FunctionCategory::Statistical,
        syntax: "AVERAGE(number1, [number2], ...)",
        description: "Returns the arithmetic mean of the arguments",
        examples: &["=AVERAGE(A1:A10)", "=AVERAGE(1, 2, 3, 4, 5)"],
    },
    FunctionInfo {
        name: "MIN",
        category: FunctionCategory::Statistical,
        syntax: "MIN(number1, [number2], ...)",
        description: "Returns the smallest value in a set of values",
        examples: &["=MIN(A1:A10)", "=MIN(1, 2, 3)"],
    },
    FunctionInfo {
        name: "MAX",
        category: FunctionCategory::Statistical,
        syntax: "MAX(number1, [number2], ...)",
        description: "Returns the largest value in a set of values",
        examples: &["=MAX(A1:A10)", "=MAX(1, 2, 3)"],
    },
    FunctionInfo {
        name: "COUNT",
        category: FunctionCategory::Statistical,
        syntax: "COUNT(value1, [value2], ...)",
        description: "Counts the number of cells containing numbers",
        examples: &["=COUNT(A1:A10)", "=COUNT(A1, B1, C1)"],
    },
    FunctionInfo {
        name: "COUNTA",
        category: FunctionCategory::Statistical,
        syntax: "COUNTA(value1, [value2], ...)",
        description: "Counts the number of non-empty cells",
        examples: &["=COUNTA(A1:A10)", "=COUNTA(A1, B1, C1)"],
    },
    FunctionInfo {
        name: "MEDIAN",
        category: FunctionCategory::Statistical,
        syntax: "MEDIAN(number1, [number2], ...)",
        description: "Returns the median (middle value) of the given numbers",
        examples: &["=MEDIAN(A1:A10)", "=MEDIAN(1, 2, 3, 4, 5)"],
    },
    FunctionInfo {
        name: "SUMIF",
        category: FunctionCategory::Statistical,
        syntax: "SUMIF(range, criteria, [sum_range])",
        description: "Sums cells that meet a specified condition",
        examples: &[
            "=SUMIF(A1:A10, \">5\")",
            "=SUMIF(A1:A10, \"Apple\", B1:B10)",
        ],
    },
    FunctionInfo {
        name: "COUNTIF",
        category: FunctionCategory::Statistical,
        syntax: "COUNTIF(range, criteria)",
        description: "Counts cells that meet a specified condition",
        examples: &["=COUNTIF(A1:A10, \">5\")", "=COUNTIF(A1:A10, \"Yes\")"],
    },
    FunctionInfo {
        name: "AVERAGEIF",
        category: FunctionCategory::Statistical,
        syntax: "AVERAGEIF(range, criteria, [average_range])",
        description: "Averages cells that meet a specified condition",
        examples: &[
            "=AVERAGEIF(A1:A10, \">5\")",
            "=AVERAGEIF(A1:A10, \"X\", B1:B10)",
        ],
    },
    FunctionInfo {
        name: "COUNTBLANK",
        category: FunctionCategory::Statistical,
        syntax: "COUNTBLANK(range)",
        description: "Counts empty cells in a range",
        examples: &["=COUNTBLANK(A1:A10)"],
    },
    FunctionInfo {
        name: "SUMIFS",
        category: FunctionCategory::Statistical,
        syntax: "SUMIFS(sum_range, criteria_range1, criteria1, ...)",
        description: "Sums cells that meet all specified conditions",
        examples: &["=SUMIFS(B1:B10, A1:A10, \"Apple\", C1:C10, \">5\")"],
    },
    FunctionInfo {
        name: "COUNTIFS",
        category: FunctionCategory::Statistical,
        syntax: "COUNTIFS(criteria_range1, criteria1, ...)",
        description: "Counts cells that meet all specified conditions",
        examples: &["=COUNTIFS(A1:A10, \"Yes\", B1:B10, \">0\")"],
    },
    FunctionInfo {
        name: "AVERAGEIFS",
        category: FunctionCategory::Statistical,
        syntax: "AVERAGEIFS(average_range, criteria_range1, criteria1, ...)",
        description: "Averages cells that meet all specified conditions",
        examples: &["=AVERAGEIFS(B1:B10, A1:A10, \"X\")"],
    },
    FunctionInfo {
        name: "STDEV",
        category: FunctionCategory::Statistical,
        syntax: "STDEV(number1, [number2], ...)",
        description: "Sample standard deviation (n-1). Same as STDEV.S",
        examples: &["=STDEV(A1:A10)", "=STDEV.S(A1:A10)"],
    },
    FunctionInfo {
        name: "STDEV.S",
        category: FunctionCategory::Statistical,
        syntax: "STDEV.S(number1, [number2], ...)",
        description: "Sample standard deviation (n-1)",
        examples: &["=STDEV.S(A1:A10)"],
    },
    FunctionInfo {
        name: "STDEVP",
        category: FunctionCategory::Statistical,
        syntax: "STDEVP(number1, [number2], ...)",
        description: "Population standard deviation. Same as STDEV.P",
        examples: &["=STDEVP(A1:A10)"],
    },
    FunctionInfo {
        name: "STDEV.P",
        category: FunctionCategory::Statistical,
        syntax: "STDEV.P(number1, [number2], ...)",
        description: "Population standard deviation",
        examples: &["=STDEV.P(A1:A10)"],
    },
    FunctionInfo {
        name: "VAR",
        category: FunctionCategory::Statistical,
        syntax: "VAR(number1, [number2], ...)",
        description: "Sample variance (n-1). Same as VAR.S",
        examples: &["=VAR(A1:A10)", "=VAR.S(A1:A10)"],
    },
    FunctionInfo {
        name: "VAR.S",
        category: FunctionCategory::Statistical,
        syntax: "VAR.S(number1, [number2], ...)",
        description: "Sample variance (n-1)",
        examples: &["=VAR.S(A1:A10)"],
    },
    FunctionInfo {
        name: "VARP",
        category: FunctionCategory::Statistical,
        syntax: "VARP(number1, [number2], ...)",
        description: "Population variance. Same as VAR.P",
        examples: &["=VARP(A1:A10)"],
    },
    FunctionInfo {
        name: "VAR.P",
        category: FunctionCategory::Statistical,
        syntax: "VAR.P(number1, [number2], ...)",
        description: "Population variance",
        examples: &["=VAR.P(A1:A10)"],
    },
    FunctionInfo {
        name: "LARGE",
        category: FunctionCategory::Statistical,
        syntax: "LARGE(array, k)",
        description: "Returns the k-th largest value in a range",
        examples: &["=LARGE(A1:A10, 2)"],
    },
    FunctionInfo {
        name: "SMALL",
        category: FunctionCategory::Statistical,
        syntax: "SMALL(array, k)",
        description: "Returns the k-th smallest value in a range",
        examples: &["=SMALL(A1:A10, 1)"],
    },
    FunctionInfo {
        name: "MODE",
        category: FunctionCategory::Statistical,
        syntax: "MODE(number1, [number2], ...)",
        description: "Returns the most frequent number; #N/A when none repeats. Same as MODE.SNGL",
        examples: &["=MODE(A1:A10)"],
    },
    FunctionInfo {
        name: "MODE.SNGL",
        category: FunctionCategory::Statistical,
        syntax: "MODE.SNGL(number1, [number2], ...)",
        description: "Returns the most frequent number; #N/A when none repeats",
        examples: &["=MODE.SNGL(A1:A10)"],
    },
    FunctionInfo {
        name: "PERCENTILE",
        category: FunctionCategory::Statistical,
        syntax: "PERCENTILE(array, k)",
        description: "Returns the k-th percentile (k from 0 to 1). Same as PERCENTILE.INC",
        examples: &["=PERCENTILE(A1:A10, 0.9)"],
    },
    FunctionInfo {
        name: "PERCENTILE.INC",
        category: FunctionCategory::Statistical,
        syntax: "PERCENTILE.INC(array, k)",
        description: "Returns the k-th percentile, k from 0 to 1 inclusive",
        examples: &["=PERCENTILE.INC(A1:A10, 0.25)"],
    },
    FunctionInfo {
        name: "PERCENTILE.EXC",
        category: FunctionCategory::Statistical,
        syntax: "PERCENTILE.EXC(array, k)",
        description: "Returns the k-th percentile, k strictly between 0 and 1",
        examples: &["=PERCENTILE.EXC(A1:A10, 0.25)"],
    },
    FunctionInfo {
        name: "QUARTILE",
        category: FunctionCategory::Statistical,
        syntax: "QUARTILE(array, quart)",
        description: "Returns a quartile (0-4). Same as QUARTILE.INC",
        examples: &["=QUARTILE(A1:A10, 1)"],
    },
    FunctionInfo {
        name: "QUARTILE.INC",
        category: FunctionCategory::Statistical,
        syntax: "QUARTILE.INC(array, quart)",
        description: "Returns a quartile, 0 (minimum) to 4 (maximum)",
        examples: &["=QUARTILE.INC(A1:A10, 3)"],
    },
    FunctionInfo {
        name: "QUARTILE.EXC",
        category: FunctionCategory::Statistical,
        syntax: "QUARTILE.EXC(array, quart)",
        description: "Returns quartile 1, 2 or 3, excluding the ends",
        examples: &["=QUARTILE.EXC(A1:A10, 1)"],
    },
    FunctionInfo {
        name: "RANK",
        category: FunctionCategory::Statistical,
        syntax: "RANK(number, ref, [order])",
        description: "Returns a number's rank in a list (0 = largest first). Same as RANK.EQ",
        examples: &["=RANK(A1, A1:A10)"],
    },
    FunctionInfo {
        name: "RANK.EQ",
        category: FunctionCategory::Statistical,
        syntax: "RANK.EQ(number, ref, [order])",
        description: "Returns a number's rank; ties share the top rank",
        examples: &["=RANK.EQ(A1, A1:A10, 1)"],
    },
    FunctionInfo {
        name: "RANK.AVG",
        category: FunctionCategory::Statistical,
        syntax: "RANK.AVG(number, ref, [order])",
        description: "Returns a number's rank; ties get their average rank",
        examples: &["=RANK.AVG(A1, A1:A10)"],
    },
    FunctionInfo {
        name: "GEOMEAN",
        category: FunctionCategory::Statistical,
        syntax: "GEOMEAN(number1, [number2], ...)",
        description: "Returns the geometric mean of positive numbers",
        examples: &["=GEOMEAN(A1:A10)"],
    },
    FunctionInfo {
        name: "HARMEAN",
        category: FunctionCategory::Statistical,
        syntax: "HARMEAN(number1, [number2], ...)",
        description: "Returns the harmonic mean of positive numbers",
        examples: &["=HARMEAN(A1:A10)"],
    },
    FunctionInfo {
        name: "AVEDEV",
        category: FunctionCategory::Statistical,
        syntax: "AVEDEV(number1, [number2], ...)",
        description: "Returns the average absolute deviation from the mean",
        examples: &["=AVEDEV(A1:A10)"],
    },
    FunctionInfo {
        name: "DEVSQ",
        category: FunctionCategory::Statistical,
        syntax: "DEVSQ(number1, [number2], ...)",
        description: "Returns the sum of squared deviations from the mean",
        examples: &["=DEVSQ(A1:A10)"],
    },
    FunctionInfo {
        name: "TRIMMEAN",
        category: FunctionCategory::Statistical,
        syntax: "TRIMMEAN(array, percent)",
        description: "Returns the mean after dropping a share of the points from both ends",
        examples: &["=TRIMMEAN(A1:A20, 0.2)"],
    },
    FunctionInfo {
        name: "STANDARDIZE",
        category: FunctionCategory::Statistical,
        syntax: "STANDARDIZE(x, mean, standard_dev)",
        description: "Returns a normalized value (z-score)",
        examples: &["=STANDARDIZE(42, 40, 1.5)"],
    },
    FunctionInfo {
        name: "CORREL",
        category: FunctionCategory::Statistical,
        syntax: "CORREL(array1, array2)",
        description: "Returns the correlation coefficient of two data sets",
        examples: &["=CORREL(A1:A10, B1:B10)"],
    },
    FunctionInfo {
        name: "PEARSON",
        category: FunctionCategory::Statistical,
        syntax: "PEARSON(array1, array2)",
        description: "Returns the Pearson correlation coefficient. Same as CORREL",
        examples: &["=PEARSON(A1:A10, B1:B10)"],
    },
    FunctionInfo {
        name: "RSQ",
        category: FunctionCategory::Statistical,
        syntax: "RSQ(known_y's, known_x's)",
        description: "Returns the square of the correlation coefficient (R squared)",
        examples: &["=RSQ(B1:B10, A1:A10)"],
    },
    FunctionInfo {
        name: "COVARIANCE.P",
        category: FunctionCategory::Statistical,
        syntax: "COVARIANCE.P(array1, array2)",
        description: "Returns the population covariance of two data sets",
        examples: &["=COVARIANCE.P(A1:A10, B1:B10)"],
    },
    FunctionInfo {
        name: "COVARIANCE.S",
        category: FunctionCategory::Statistical,
        syntax: "COVARIANCE.S(array1, array2)",
        description: "Returns the sample covariance of two data sets",
        examples: &["=COVARIANCE.S(A1:A10, B1:B10)"],
    },
    FunctionInfo {
        name: "COVAR",
        category: FunctionCategory::Statistical,
        syntax: "COVAR(array1, array2)",
        description: "Returns the population covariance. Same as COVARIANCE.P",
        examples: &["=COVAR(A1:A10, B1:B10)"],
    },
    FunctionInfo {
        name: "SLOPE",
        category: FunctionCategory::Statistical,
        syntax: "SLOPE(known_y's, known_x's)",
        description: "Returns the slope of the linear regression line",
        examples: &["=SLOPE(B1:B10, A1:A10)"],
    },
    FunctionInfo {
        name: "INTERCEPT",
        category: FunctionCategory::Statistical,
        syntax: "INTERCEPT(known_y's, known_x's)",
        description: "Returns where the linear regression line crosses the y-axis",
        examples: &["=INTERCEPT(B1:B10, A1:A10)"],
    },
    FunctionInfo {
        name: "STEYX",
        category: FunctionCategory::Statistical,
        syntax: "STEYX(known_y's, known_x's)",
        description: "Returns the standard error of the predicted y for each x in a regression",
        examples: &["=STEYX(B1:B10, A1:A10)"],
    },
    FunctionInfo {
        name: "FORECAST",
        category: FunctionCategory::Statistical,
        syntax: "FORECAST(x, known_y's, known_x's)",
        description: "Predicts a y value for x from a linear trend. Same as FORECAST.LINEAR",
        examples: &["=FORECAST(30, B1:B10, A1:A10)"],
    },
    FunctionInfo {
        name: "FORECAST.LINEAR",
        category: FunctionCategory::Statistical,
        syntax: "FORECAST.LINEAR(x, known_y's, known_x's)",
        description: "Predicts a y value for x from a linear trend",
        examples: &["=FORECAST.LINEAR(30, B1:B10, A1:A10)"],
    },
    FunctionInfo {
        name: "MAXIFS",
        category: FunctionCategory::Statistical,
        syntax: "MAXIFS(max_range, criteria_range1, criteria1, ...)",
        description: "Returns the largest number among cells that meet all conditions (0 if none)",
        examples: &["=MAXIFS(B1:B10, A1:A10, \"East\")"],
    },
    FunctionInfo {
        name: "MINIFS",
        category: FunctionCategory::Statistical,
        syntax: "MINIFS(min_range, criteria_range1, criteria1, ...)",
        description: "Returns the smallest number among cells that meet all conditions (0 if none)",
        examples: &["=MINIFS(B1:B10, A1:A10, \">5\")"],
    },
    FunctionInfo {
        name: "AVERAGEA",
        category: FunctionCategory::Statistical,
        syntax: "AVERAGEA(value1, [value2], ...)",
        description: "Averages values, counting text in cells as 0 and TRUE/FALSE as 1/0",
        examples: &["=AVERAGEA(A1:A10)"],
    },
    FunctionInfo {
        name: "MAXA",
        category: FunctionCategory::Statistical,
        syntax: "MAXA(value1, [value2], ...)",
        description: "Returns the largest value, counting text in cells as 0 and TRUE/FALSE as 1/0",
        examples: &["=MAXA(A1:A10)"],
    },
    FunctionInfo {
        name: "MINA",
        category: FunctionCategory::Statistical,
        syntax: "MINA(value1, [value2], ...)",
        description: "Returns the smallest value, counting text in cells as 0 and TRUE/FALSE as 1/0",
        examples: &["=MINA(A1:A10)"],
    },
    // ===== Financial Functions =====
    FunctionInfo {
        name: "PMT",
        category: FunctionCategory::Financial,
        syntax: "PMT(rate, nper, pv, [fv], [type])",
        description: "Returns the payment per period for a loan or annuity (type 1 = payments at the start)",
        examples: &["=PMT(5%/12, 360, 200000)"],
    },
    FunctionInfo {
        name: "IPMT",
        category: FunctionCategory::Financial,
        syntax: "IPMT(rate, per, nper, pv, [fv], [type])",
        description: "Returns the interest part of one period's payment",
        examples: &["=IPMT(10%/12, 1, 36, 8000)"],
    },
    FunctionInfo {
        name: "PPMT",
        category: FunctionCategory::Financial,
        syntax: "PPMT(rate, per, nper, pv, [fv], [type])",
        description: "Returns the principal part of one period's payment",
        examples: &["=PPMT(10%/12, 1, 24, 2000)"],
    },
    FunctionInfo {
        name: "CUMIPMT",
        category: FunctionCategory::Financial,
        syntax: "CUMIPMT(rate, nper, pv, start_period, end_period, type)",
        description: "Returns the interest paid between two periods",
        examples: &["=CUMIPMT(9%/12, 360, 125000, 13, 24, 0)"],
    },
    FunctionInfo {
        name: "CUMPRINC",
        category: FunctionCategory::Financial,
        syntax: "CUMPRINC(rate, nper, pv, start_period, end_period, type)",
        description: "Returns the principal paid between two periods",
        examples: &["=CUMPRINC(9%/12, 360, 125000, 13, 24, 0)"],
    },
    FunctionInfo {
        name: "FV",
        category: FunctionCategory::Financial,
        syntax: "FV(rate, nper, pmt, [pv], [type])",
        description: "Returns the future value of an investment",
        examples: &["=FV(6%/12, 10, -200, -500, 1)"],
    },
    FunctionInfo {
        name: "PV",
        category: FunctionCategory::Financial,
        syntax: "PV(rate, nper, pmt, [fv], [type])",
        description: "Returns the present value of an investment",
        examples: &["=PV(8%/12, 240, 500)"],
    },
    FunctionInfo {
        name: "NPER",
        category: FunctionCategory::Financial,
        syntax: "NPER(rate, pmt, pv, [fv], [type])",
        description: "Returns the number of periods for an investment",
        examples: &["=NPER(1%, -100, -1000, 10000)"],
    },
    FunctionInfo {
        name: "RATE",
        category: FunctionCategory::Financial,
        syntax: "RATE(nper, pmt, pv, [fv], [type], [guess])",
        description: "Returns the interest rate per period of an annuity",
        examples: &["=RATE(48, -200, 8000)*12"],
    },
    FunctionInfo {
        name: "NPV",
        category: FunctionCategory::Financial,
        syntax: "NPV(rate, value1, [value2], ...)",
        description: "Returns the net present value of periodic cash flows, the first one period out",
        examples: &["=NPV(10%, -10000, 3000, 4200, 6800)"],
    },
    FunctionInfo {
        name: "IRR",
        category: FunctionCategory::Financial,
        syntax: "IRR(values, [guess])",
        description: "Returns the internal rate of return of periodic cash flows",
        examples: &["=IRR(A1:A6)"],
    },
    FunctionInfo {
        name: "MIRR",
        category: FunctionCategory::Financial,
        syntax: "MIRR(values, finance_rate, reinvest_rate)",
        description: "Returns the modified internal rate of return",
        examples: &["=MIRR(A1:A6, 10%, 12%)"],
    },
    FunctionInfo {
        name: "XNPV",
        category: FunctionCategory::Financial,
        syntax: "XNPV(rate, values, dates)",
        description: "Returns the net present value of cash flows on given dates",
        examples: &["=XNPV(9%, A1:A5, B1:B5)"],
    },
    FunctionInfo {
        name: "XIRR",
        category: FunctionCategory::Financial,
        syntax: "XIRR(values, dates, [guess])",
        description: "Returns the internal rate of return of cash flows on given dates",
        examples: &["=XIRR(A1:A5, B1:B5)"],
    },
    FunctionInfo {
        name: "SLN",
        category: FunctionCategory::Financial,
        syntax: "SLN(cost, salvage, life)",
        description: "Returns straight-line depreciation for one period",
        examples: &["=SLN(30000, 7500, 10)"],
    },
    FunctionInfo {
        name: "SYD",
        category: FunctionCategory::Financial,
        syntax: "SYD(cost, salvage, life, per)",
        description: "Returns sum-of-years' digits depreciation for a period",
        examples: &["=SYD(30000, 7500, 10, 1)"],
    },
    FunctionInfo {
        name: "DB",
        category: FunctionCategory::Financial,
        syntax: "DB(cost, salvage, life, period, [month])",
        description: "Returns fixed-declining balance depreciation for a period",
        examples: &["=DB(1000000, 100000, 6, 1, 7)"],
    },
    FunctionInfo {
        name: "DDB",
        category: FunctionCategory::Financial,
        syntax: "DDB(cost, salvage, life, period, [factor])",
        description: "Returns double-declining balance (or another factor) depreciation for a period",
        examples: &["=DDB(2400, 300, 10, 1)"],
    },
    // ===== Logical Functions =====
    FunctionInfo {
        name: "IF",
        category: FunctionCategory::Logical,
        syntax: "IF(condition, value_if_true, [value_if_false])",
        description: "Returns one value if a condition is true, another if false",
        examples: &[
            "=IF(A1>10, \"Big\", \"Small\")",
            "=IF(A1=B1, \"Match\", \"No match\")",
        ],
    },
    FunctionInfo {
        name: "AND",
        category: FunctionCategory::Logical,
        syntax: "AND(logical1, [logical2], ...)",
        description: "Returns TRUE if all arguments are true; ranges count their logicals and numbers",
        examples: &["=AND(A1>0, B1>0)", "=AND(A1:A10)"],
    },
    FunctionInfo {
        name: "OR",
        category: FunctionCategory::Logical,
        syntax: "OR(logical1, [logical2], ...)",
        description: "Returns TRUE if any argument is true; ranges count their logicals and numbers",
        examples: &["=OR(A1>0, B1>0)", "=OR(FALSE, FALSE, TRUE)"],
    },
    FunctionInfo {
        name: "NOT",
        category: FunctionCategory::Logical,
        syntax: "NOT(logical)",
        description: "Reverses the logic of its argument",
        examples: &["=NOT(TRUE)", "=NOT(A1>10)"],
    },
    FunctionInfo {
        name: "XOR",
        category: FunctionCategory::Logical,
        syntax: "XOR(logical1, [logical2], ...)",
        description: "Returns TRUE if an odd number of arguments are true",
        examples: &["=XOR(TRUE, FALSE)", "=XOR(A1>0, B1>0, C1>0)"],
    },
    FunctionInfo {
        name: "TRUE",
        category: FunctionCategory::Logical,
        syntax: "TRUE()",
        description: "Returns the logical value TRUE",
        examples: &["=TRUE()"],
    },
    FunctionInfo {
        name: "FALSE",
        category: FunctionCategory::Logical,
        syntax: "FALSE()",
        description: "Returns the logical value FALSE",
        examples: &["=FALSE()"],
    },
    FunctionInfo {
        name: "IFERROR",
        category: FunctionCategory::Logical,
        syntax: "IFERROR(value, value_if_error)",
        description: "Returns value_if_error if value is an error, otherwise returns value",
        examples: &[
            "=IFERROR(A1/B1, 0)",
            "=IFERROR(VLOOKUP(...), \"Not found\")",
        ],
    },
    FunctionInfo {
        name: "IFNA",
        category: FunctionCategory::Logical,
        syntax: "IFNA(value, value_if_na)",
        description: "Returns value_if_na if value is #N/A, otherwise returns value",
        examples: &["=IFNA(VLOOKUP(...), \"Not found\")"],
    },
    FunctionInfo {
        name: "IFS",
        category: FunctionCategory::Logical,
        syntax: "IFS(condition1, value1, [condition2, value2], ...)",
        description: "Checks multiple conditions and returns the first true result",
        examples: &["=IFS(A1>90, \"A\", A1>80, \"B\", A1>70, \"C\", TRUE, \"F\")"],
    },
    FunctionInfo {
        name: "SWITCH",
        category: FunctionCategory::Logical,
        syntax: "SWITCH(expression, value1, result1, [value2, result2], ..., [default])",
        description: "Evaluates expression against a list of values and returns the matching result",
        examples: &["=SWITCH(A1, 1, \"One\", 2, \"Two\", \"Other\")"],
    },
    FunctionInfo {
        name: "CHOOSE",
        category: FunctionCategory::Logical,
        syntax: "CHOOSE(index, value1, [value2], ...)",
        description: "Returns the value at the specified index position",
        examples: &["=CHOOSE(2, \"A\", \"B\", \"C\")", "=CHOOSE(A1, 10, 20, 30)"],
    },
    // ===== Text Functions =====
    FunctionInfo {
        name: "LEN",
        category: FunctionCategory::Text,
        syntax: "LEN(text)",
        description: "Returns the number of characters in a text string",
        examples: &["=LEN(\"Hello\")", "=LEN(A1)"],
    },
    FunctionInfo {
        name: "UPPER",
        category: FunctionCategory::Text,
        syntax: "UPPER(text)",
        description: "Converts text to uppercase",
        examples: &["=UPPER(\"hello\")", "=UPPER(A1)"],
    },
    FunctionInfo {
        name: "LOWER",
        category: FunctionCategory::Text,
        syntax: "LOWER(text)",
        description: "Converts text to lowercase",
        examples: &["=LOWER(\"HELLO\")", "=LOWER(A1)"],
    },
    FunctionInfo {
        name: "PROPER",
        category: FunctionCategory::Text,
        syntax: "PROPER(text)",
        description: "Capitalizes each letter that follows anything but a letter, and lowercases the rest",
        examples: &["=PROPER(\"hello world\")", "=PROPER(A1)"],
    },
    FunctionInfo {
        name: "TRIM",
        category: FunctionCategory::Text,
        syntax: "TRIM(text)",
        description: "Removes spaces from text except single spaces between words",
        examples: &["=TRIM(\"  hello  \")", "=TRIM(A1)"],
    },
    FunctionInfo {
        name: "LEFT",
        category: FunctionCategory::Text,
        syntax: "LEFT(text, [num_chars])",
        description: "Returns the leftmost characters from a text string",
        examples: &["=LEFT(\"Hello\", 2)", "=LEFT(A1, 3)"],
    },
    FunctionInfo {
        name: "RIGHT",
        category: FunctionCategory::Text,
        syntax: "RIGHT(text, [num_chars])",
        description: "Returns the rightmost characters from a text string",
        examples: &["=RIGHT(\"Hello\", 2)", "=RIGHT(A1, 3)"],
    },
    FunctionInfo {
        name: "MID",
        category: FunctionCategory::Text,
        syntax: "MID(text, start_num, num_chars)",
        description: "Returns characters from the middle of a text string",
        examples: &["=MID(\"Hello\", 2, 3)", "=MID(A1, 1, 5)"],
    },
    FunctionInfo {
        name: "CONCATENATE",
        category: FunctionCategory::Text,
        syntax: "CONCATENATE(text1, [text2], ...)",
        description: "Joins several text strings into one",
        examples: &[
            "=CONCATENATE(A1, \" \", B1)",
            "=CONCATENATE(\"Hello\", \" \", \"World\")",
        ],
    },
    FunctionInfo {
        name: "CONCAT",
        category: FunctionCategory::Text,
        syntax: "CONCAT(text1, [text2], ...)",
        description: "Joins several text strings, or every cell of a range, into one",
        examples: &["=CONCAT(A1:C1)", "=CONCAT(\"Hello\", \"World\")"],
    },
    FunctionInfo {
        name: "FIND",
        category: FunctionCategory::Text,
        syntax: "FIND(find_text, within_text, [start_num])",
        description: "Finds one text string within another (case-sensitive)",
        examples: &["=FIND(\"l\", \"Hello\")", "=FIND(A1, B1)"],
    },
    FunctionInfo {
        name: "SEARCH",
        category: FunctionCategory::Text,
        syntax: "SEARCH(find_text, within_text, [start_num])",
        description: "Finds one text string within another (case-insensitive; * and ? are wildcards, ~ escapes them)",
        examples: &["=SEARCH(\"L\", \"Hello\")", "=SEARCH(\"b*d\", \"abcde\")"],
    },
    FunctionInfo {
        name: "SUBSTITUTE",
        category: FunctionCategory::Text,
        syntax: "SUBSTITUTE(text, old_text, new_text, [instance_num])",
        description: "Replaces occurrences of old_text with new_text",
        examples: &[
            "=SUBSTITUTE(A1, \"old\", \"new\")",
            "=SUBSTITUTE(\"aaa\", \"a\", \"b\", 2)",
        ],
    },
    FunctionInfo {
        name: "REPLACE",
        category: FunctionCategory::Text,
        syntax: "REPLACE(old_text, start_num, num_chars, new_text)",
        description: "Replaces characters within text",
        examples: &[
            "=REPLACE(\"Hello\", 1, 2, \"XX\")",
            "=REPLACE(A1, 1, 3, \"New\")",
        ],
    },
    FunctionInfo {
        name: "REPT",
        category: FunctionCategory::Text,
        syntax: "REPT(text, number_times)",
        description: "Repeats text a specified number of times",
        examples: &["=REPT(\"*\", 10)", "=REPT(A1, 3)"],
    },
    FunctionInfo {
        name: "EXACT",
        category: FunctionCategory::Text,
        syntax: "EXACT(text1, text2)",
        description: "Checks if two text strings are exactly the same (case-sensitive)",
        examples: &["=EXACT(\"Hello\", \"hello\")", "=EXACT(A1, B1)"],
    },
    FunctionInfo {
        name: "VALUE",
        category: FunctionCategory::Text,
        syntax: "VALUE(text)",
        description: "Converts a text string to a number",
        examples: &["=VALUE(\"123\")", "=VALUE(A1)"],
    },
    FunctionInfo {
        name: "TEXT",
        category: FunctionCategory::Text,
        syntax: "TEXT(value, format_text)",
        description: "Converts a value to text using a number, percent, or date format",
        examples: &[
            "=TEXT(1234.5, \"#,##0.00\")",
            "=TEXT(0.5, \"0%\")",
            "=TEXT(DATE(2024,8,18), \"yyyy-mm-dd\")",
        ],
    },
    FunctionInfo {
        name: "CHAR",
        category: FunctionCategory::Text,
        syntax: "CHAR(number)",
        description: "Returns the character specified by a number (1-255)",
        examples: &["=CHAR(65)", "=CHAR(10)"],
    },
    FunctionInfo {
        name: "CODE",
        category: FunctionCategory::Text,
        syntax: "CODE(text)",
        description: "Returns the numeric code for the first character",
        examples: &["=CODE(\"A\")", "=CODE(A1)"],
    },
    FunctionInfo {
        name: "TEXTJOIN",
        category: FunctionCategory::Text,
        syntax: "TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)",
        description: "Joins text and ranges with a delimiter, optionally skipping empty cells",
        examples: &["=TEXTJOIN(\", \", TRUE, A1:A10)"],
    },
    FunctionInfo {
        name: "CLEAN",
        category: FunctionCategory::Text,
        syntax: "CLEAN(text)",
        description: "Removes non-printable characters (codes 0-31)",
        examples: &["=CLEAN(A1)"],
    },
    FunctionInfo {
        name: "T",
        category: FunctionCategory::Text,
        syntax: "T(value)",
        description: "Returns text unchanged, or empty text for anything else",
        examples: &["=T(A1)"],
    },
    FunctionInfo {
        name: "DOLLAR",
        category: FunctionCategory::Text,
        syntax: "DOLLAR(number, [decimals])",
        description: "Formats a number as currency text, e.g. $1,234.57",
        examples: &["=DOLLAR(1234.567, 2)"],
    },
    FunctionInfo {
        name: "FIXED",
        category: FunctionCategory::Text,
        syntax: "FIXED(number, [decimals], [no_commas])",
        description: "Formats a number as text with fixed decimals",
        examples: &["=FIXED(1234.567, 1)", "=FIXED(1234.567, -1, TRUE)"],
    },
    FunctionInfo {
        name: "UNICHAR",
        category: FunctionCategory::Text,
        syntax: "UNICHAR(number)",
        description: "Returns the Unicode character for a code point",
        examples: &["=UNICHAR(66)"],
    },
    FunctionInfo {
        name: "UNICODE",
        category: FunctionCategory::Text,
        syntax: "UNICODE(text)",
        description: "Returns the code point of the first character",
        examples: &["=UNICODE(\"B\")"],
    },
    FunctionInfo {
        name: "NUMBERVALUE",
        category: FunctionCategory::Text,
        syntax: "NUMBERVALUE(text, [decimal_separator], [group_separator])",
        description: "Converts text to a number with the given separators",
        examples: &[
            "=NUMBERVALUE(\"2.500,27\", \",\", \".\")",
            "=NUMBERVALUE(\"3.5%\")",
        ],
    },
    FunctionInfo {
        name: "TEXTBEFORE",
        category: FunctionCategory::Text,
        syntax: "TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])",
        description: "Returns the text before a delimiter; a negative instance counts from the end",
        examples: &["=TEXTBEFORE(A1, \" \")", "=TEXTBEFORE(A1, \"-\", -1)"],
    },
    FunctionInfo {
        name: "TEXTAFTER",
        category: FunctionCategory::Text,
        syntax: "TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])",
        description: "Returns the text after a delimiter; a negative instance counts from the end",
        examples: &["=TEXTAFTER(A1, \"@\")", "=TEXTAFTER(A1, \" \", -1)"],
    },
    // ===== Lookup Functions =====
    FunctionInfo {
        name: "VLOOKUP",
        category: FunctionCategory::Lookup,
        syntax: "VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])",
        description: "Looks up a value in the first column and returns a value in the same row",
        examples: &[
            "=VLOOKUP(A1, B1:D10, 2, FALSE)",
            "=VLOOKUP(\"Apple\", A1:C100, 3, TRUE)",
        ],
    },
    FunctionInfo {
        name: "HLOOKUP",
        category: FunctionCategory::Lookup,
        syntax: "HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])",
        description: "Looks up a value in the first row and returns a value in the same column",
        examples: &[
            "=HLOOKUP(A1, A1:Z3, 2, FALSE)",
            "=HLOOKUP(\"Q1\", A1:D10, 3, TRUE)",
        ],
    },
    FunctionInfo {
        name: "INDEX",
        category: FunctionCategory::Lookup,
        syntax: "INDEX(array, row_num, [column_num])",
        description: "Returns the value at a given position in a range",
        examples: &["=INDEX(A1:C10, 2, 3)", "=INDEX(A1:A10, 5)"],
    },
    FunctionInfo {
        name: "MATCH",
        category: FunctionCategory::Lookup,
        syntax: "MATCH(lookup_value, lookup_array, [match_type])",
        description: "Returns the relative position of an item in a range",
        examples: &["=MATCH(\"Apple\", A1:A10, 0)", "=MATCH(5, B1:B100, 1)"],
    },
    FunctionInfo {
        name: "ROW",
        category: FunctionCategory::Lookup,
        syntax: "ROW([reference])",
        description: "Returns the row number of a reference",
        examples: &["=ROW(A5)", "=ROW()"],
    },
    FunctionInfo {
        name: "COLUMN",
        category: FunctionCategory::Lookup,
        syntax: "COLUMN([reference])",
        description: "Returns the column number of a reference",
        examples: &["=COLUMN(C1)", "=COLUMN()"],
    },
    FunctionInfo {
        name: "ROWS",
        category: FunctionCategory::Lookup,
        syntax: "ROWS(array)",
        description: "Returns the number of rows in a reference",
        examples: &["=ROWS(A1:A10)", "=ROWS(A1:C100)"],
    },
    FunctionInfo {
        name: "COLUMNS",
        category: FunctionCategory::Lookup,
        syntax: "COLUMNS(array)",
        description: "Returns the number of columns in a reference",
        examples: &["=COLUMNS(A1:C1)", "=COLUMNS(A1:Z100)"],
    },
    FunctionInfo {
        name: "LOOKUP",
        category: FunctionCategory::Lookup,
        syntax: "LOOKUP(lookup_value, lookup_vector, [result_vector])",
        description: "Finds the largest value at or below lookup_value in a sorted row or column and returns the matching result",
        examples: &["=LOOKUP(4.19, A1:A5, B1:B5)", "=LOOKUP(\"C\", A1:D2)"],
    },
    FunctionInfo {
        name: "ADDRESS",
        category: FunctionCategory::Lookup,
        syntax: "ADDRESS(row, column, [abs_num], [a1], [sheet_text])",
        description: "Returns a cell address as text",
        examples: &["=ADDRESS(2, 3)", "=ADDRESS(2, 3, 4, TRUE, \"Data\")"],
    },
    FunctionInfo {
        name: "INDIRECT",
        category: FunctionCategory::Lookup,
        syntax: "INDIRECT(ref_text, [a1])",
        description: "Returns the reference named by A1-style text. Recalculates after every edit",
        examples: &["=INDIRECT(\"B2\")", "=SUM(INDIRECT(\"Sheet2!A1:A10\"))"],
    },
    FunctionInfo {
        name: "OFFSET",
        category: FunctionCategory::Lookup,
        syntax: "OFFSET(reference, rows, cols, [height], [width])",
        description: "Returns a reference moved and resized from a starting one. Recalculates after every edit",
        examples: &["=OFFSET(A1, 2, 1)", "=SUM(OFFSET(A1, 0, 0, 5, 1))"],
    },
    FunctionInfo {
        name: "FORMULATEXT",
        category: FunctionCategory::Lookup,
        syntax: "FORMULATEXT(reference)",
        description: "Returns the formula in a cell as text",
        examples: &["=FORMULATEXT(B1)"],
    },
    FunctionInfo {
        name: "HYPERLINK",
        category: FunctionCategory::Lookup,
        syntax: "HYPERLINK(link_location, [friendly_name])",
        description: "Shows a link's friendly name, or the link itself",
        examples: &["=HYPERLINK(\"https://example.com\", \"Report\")"],
    },
    FunctionInfo {
        name: "SHEET",
        category: FunctionCategory::Lookup,
        syntax: "SHEET([value])",
        description: "Returns the sheet number of this sheet, a reference, or a sheet name",
        examples: &["=SHEET()", "=SHEET(\"Data\")"],
    },
    FunctionInfo {
        name: "SHEETS",
        category: FunctionCategory::Lookup,
        syntax: "SHEETS([reference])",
        description: "Returns the number of sheets in the workbook",
        examples: &["=SHEETS()"],
    },
    // ===== Date & Time Functions =====
    FunctionInfo {
        name: "DATE",
        category: FunctionCategory::DateTime,
        syntax: "DATE(year, month, day)",
        description: "Creates a date from year, month, and day components",
        examples: &["=DATE(2024, 1, 15)", "=DATE(A1, B1, C1)"],
    },
    FunctionInfo {
        name: "TODAY",
        category: FunctionCategory::DateTime,
        syntax: "TODAY()",
        description: "Returns the current date in the time zone set under View > Time Zone",
        examples: &["=TODAY()", "=TODAY()+7"],
    },
    FunctionInfo {
        name: "NOW",
        category: FunctionCategory::DateTime,
        syntax: "NOW()",
        description: "Returns the current date and time in the time zone set under View > Time Zone",
        examples: &["=NOW()"],
    },
    FunctionInfo {
        name: "YEAR",
        category: FunctionCategory::DateTime,
        syntax: "YEAR(serial_number)",
        description: "Returns the year from a date",
        examples: &["=YEAR(TODAY())", "=YEAR(A1)"],
    },
    FunctionInfo {
        name: "MONTH",
        category: FunctionCategory::DateTime,
        syntax: "MONTH(serial_number)",
        description: "Returns the month from a date (1-12)",
        examples: &["=MONTH(TODAY())", "=MONTH(A1)"],
    },
    FunctionInfo {
        name: "DAY",
        category: FunctionCategory::DateTime,
        syntax: "DAY(serial_number)",
        description: "Returns the day from a date (1-31)",
        examples: &["=DAY(TODAY())", "=DAY(A1)"],
    },
    FunctionInfo {
        name: "TIME",
        category: FunctionCategory::DateTime,
        syntax: "TIME(hour, minute, second)",
        description: "Returns a time as a fraction of a day",
        examples: &["=TIME(12, 30, 0)"],
    },
    FunctionInfo {
        name: "HOUR",
        category: FunctionCategory::DateTime,
        syntax: "HOUR(serial_number)",
        description: "Returns the hour (0-23) of a time",
        examples: &["=HOUR(NOW())", "=HOUR(\"6:45 PM\")"],
    },
    FunctionInfo {
        name: "MINUTE",
        category: FunctionCategory::DateTime,
        syntax: "MINUTE(serial_number)",
        description: "Returns the minute (0-59) of a time",
        examples: &["=MINUTE(A1)"],
    },
    FunctionInfo {
        name: "SECOND",
        category: FunctionCategory::DateTime,
        syntax: "SECOND(serial_number)",
        description: "Returns the second (0-59) of a time",
        examples: &["=SECOND(A1)"],
    },
    FunctionInfo {
        name: "WEEKDAY",
        category: FunctionCategory::DateTime,
        syntax: "WEEKDAY(serial_number, [return_type])",
        description: "Returns the day of the week: 1 = Sunday by default; type 2 starts on Monday, type 3 counts from 0",
        examples: &["=WEEKDAY(TODAY())", "=WEEKDAY(A1, 2)"],
    },
    FunctionInfo {
        name: "WEEKNUM",
        category: FunctionCategory::DateTime,
        syntax: "WEEKNUM(serial_number, [return_type])",
        description: "Returns the week of the year; type 2 starts weeks on Monday, 21 is the ISO week",
        examples: &["=WEEKNUM(A1)", "=WEEKNUM(A1, 21)"],
    },
    FunctionInfo {
        name: "EDATE",
        category: FunctionCategory::DateTime,
        syntax: "EDATE(start_date, months)",
        description: "Returns the date a number of months before or after a date",
        examples: &["=EDATE(A1, 3)"],
    },
    FunctionInfo {
        name: "EOMONTH",
        category: FunctionCategory::DateTime,
        syntax: "EOMONTH(start_date, months)",
        description: "Returns the last day of the month a number of months away",
        examples: &["=EOMONTH(A1, 0)"],
    },
    FunctionInfo {
        name: "DATEDIF",
        category: FunctionCategory::DateTime,
        syntax: "DATEDIF(start_date, end_date, unit)",
        description: "Returns the difference in whole \"Y\", \"M\" or \"D\", or \"YM\", \"YD\", \"MD\" ignoring larger units",
        examples: &["=DATEDIF(A1, TODAY(), \"Y\")"],
    },
    FunctionInfo {
        name: "DATEVALUE",
        category: FunctionCategory::DateTime,
        syntax: "DATEVALUE(date_text)",
        description: "Converts date text such as \"2024-01-15\" or \"15-Jan-2024\" to a date serial number",
        examples: &["=DATEVALUE(\"8/22/2011\")"],
    },
    FunctionInfo {
        name: "TIMEVALUE",
        category: FunctionCategory::DateTime,
        syntax: "TIMEVALUE(time_text)",
        description: "Converts time text to a fraction of a day",
        examples: &["=TIMEVALUE(\"6:35 PM\")"],
    },
    FunctionInfo {
        name: "DAYS",
        category: FunctionCategory::DateTime,
        syntax: "DAYS(end_date, start_date)",
        description: "Returns the number of days between two dates",
        examples: &["=DAYS(B1, A1)"],
    },
    FunctionInfo {
        name: "DAYS360",
        category: FunctionCategory::DateTime,
        syntax: "DAYS360(start_date, end_date, [method])",
        description: "Returns the days between two dates on a 360-day year (TRUE for the European method)",
        examples: &["=DAYS360(A1, B1)"],
    },
    FunctionInfo {
        name: "NETWORKDAYS",
        category: FunctionCategory::DateTime,
        syntax: "NETWORKDAYS(start_date, end_date, [holidays])",
        description: "Returns the number of weekdays between two dates, less holidays",
        examples: &["=NETWORKDAYS(A1, B1, C1:C10)"],
    },
    FunctionInfo {
        name: "WORKDAY",
        category: FunctionCategory::DateTime,
        syntax: "WORKDAY(start_date, days, [holidays])",
        description: "Returns the date a number of weekdays away, skipping holidays",
        examples: &["=WORKDAY(A1, 10)"],
    },
    FunctionInfo {
        name: "YEARFRAC",
        category: FunctionCategory::DateTime,
        syntax: "YEARFRAC(start_date, end_date, [basis])",
        description: "Returns the fraction of a year between two dates (basis 0-4)",
        examples: &["=YEARFRAC(A1, B1, 1)"],
    },
    // ===== Information Functions =====
    FunctionInfo {
        name: "ISBLANK",
        category: FunctionCategory::Info,
        syntax: "ISBLANK(value)",
        description: "Returns TRUE if the cell is empty",
        examples: &["=ISBLANK(A1)"],
    },
    FunctionInfo {
        name: "ISERROR",
        category: FunctionCategory::Info,
        syntax: "ISERROR(value)",
        description: "Returns TRUE if the value is any error",
        examples: &["=ISERROR(A1/B1)", "=ISERROR(A1)"],
    },
    FunctionInfo {
        name: "ISNA",
        category: FunctionCategory::Info,
        syntax: "ISNA(value)",
        description: "Returns TRUE if the value is #N/A error",
        examples: &["=ISNA(VLOOKUP(...))", "=ISNA(A1)"],
    },
    FunctionInfo {
        name: "ISNUMBER",
        category: FunctionCategory::Info,
        syntax: "ISNUMBER(value)",
        description: "Returns TRUE if the value is a number",
        examples: &["=ISNUMBER(A1)", "=ISNUMBER(\"123\")"],
    },
    FunctionInfo {
        name: "ISTEXT",
        category: FunctionCategory::Info,
        syntax: "ISTEXT(value)",
        description: "Returns TRUE if the value is text",
        examples: &["=ISTEXT(A1)", "=ISTEXT(123)"],
    },
    FunctionInfo {
        name: "ISLOGICAL",
        category: FunctionCategory::Info,
        syntax: "ISLOGICAL(value)",
        description: "Returns TRUE if the value is a logical value (TRUE or FALSE)",
        examples: &["=ISLOGICAL(TRUE)", "=ISLOGICAL(A1)"],
    },
    FunctionInfo {
        name: "NA",
        category: FunctionCategory::Info,
        syntax: "NA()",
        description: "Returns the #N/A error value",
        examples: &["=NA()", "=IF(A1=\"\", NA(), A1)"],
    },
    FunctionInfo {
        name: "TYPE",
        category: FunctionCategory::Info,
        syntax: "TYPE(value)",
        description: "Returns a number indicating the type of value (1=number, 2=text, 4=logical, 16=error)",
        examples: &["=TYPE(A1)", "=TYPE(\"Hello\")"],
    },
    FunctionInfo {
        name: "N",
        category: FunctionCategory::Info,
        syntax: "N(value)",
        description: "Converts a value to a number",
        examples: &["=N(TRUE)", "=N(A1)"],
    },
    FunctionInfo {
        name: "ISEVEN",
        category: FunctionCategory::Info,
        syntax: "ISEVEN(number)",
        description: "Returns TRUE if the number is even",
        examples: &["=ISEVEN(A1)"],
    },
    FunctionInfo {
        name: "ISODD",
        category: FunctionCategory::Info,
        syntax: "ISODD(number)",
        description: "Returns TRUE if the number is odd",
        examples: &["=ISODD(A1)"],
    },
    FunctionInfo {
        name: "ISERR",
        category: FunctionCategory::Info,
        syntax: "ISERR(value)",
        description: "Returns TRUE if the value is any error except #N/A",
        examples: &["=ISERR(A1/B1)"],
    },
    FunctionInfo {
        name: "ERROR.TYPE",
        category: FunctionCategory::Info,
        syntax: "ERROR.TYPE(error_val)",
        description: "Returns a number for an error: 1 #NULL!, 2 #DIV/0!, 3 #VALUE!, 4 #REF!, 5 #NAME?, 6 #NUM!, 7 #N/A",
        examples: &["=ERROR.TYPE(A1)"],
    },
    FunctionInfo {
        name: "ISFORMULA",
        category: FunctionCategory::Info,
        syntax: "ISFORMULA(reference)",
        description: "Returns TRUE if the cell holds a formula",
        examples: &["=ISFORMULA(A1)"],
    },
];
